### ISSUE TITLE
First request for blocks/transactions failed due to uninitialized constant

### ISSUE THREAD

**Issue by rktoomey** [coinbase/toshi#157]
The first hit to `/api/v0/blocks/XXX/transactions` fails because of an uninitialized constant.  Subsequent requests succeed.

This seems like a recent reversion, within the past week or so.

```
14:09:13 web.1                | NameError - uninitialized constant Toshi::Models::Transaction:
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sidekiq-3.2.1/lib/sidekiq/core_ext.rb:98:in `block in constantize'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sidekiq-3.2.1/lib/sidekiq/core_ext.rb:97:in `each'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sidekiq-3.2.1/lib/sidekiq/core_ext.rb:97:in `constantize'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sequel-4.13.0/lib/sequel/model/inflections.rb:123:in `constantize'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sequel-4.13.0/lib/sequel/model/associations.rb:53:in `block in associated_class'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sequel-4.13.0/lib/sequel/model/associations.rb:489:in `block (2 levels) in cached_fetch'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sequel-4.13.0/lib/sequel/model/associations.rb:489:in `fetch'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sequel-4.13.0/lib/sequel/model/associations.rb:489:in `block in cached_fetch'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sequel-4.13.0/lib/sequel/model/associations.rb:487:in `fetch'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sequel-4.13.0/lib/sequel/model/associations.rb:487:in `cached_fetch'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sequel-4.13.0/lib/sequel/model/associations.rb:53:in `associated_class'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sequel-4.13.0/lib/sequel/model/associations.rb:503:in `_associated_dataset'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sequel-4.13.0/lib/sequel/model/associations.rb:1215:in `_associated_dataset'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sequel-4.13.0/lib/sequel/model/associations.rb:60:in `block in associated_dataset'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sequel-4.13.0/lib/sequel/model/associations.rb:489:in `block (2 levels) in cached_fetch'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sequel-4.13.0/lib/sequel/model/associations.rb:489:in `fetch'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sequel-4.13.0/lib/sequel/model/associations.rb:489:in `block in cached_fetch'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sequel-4.13.0/lib/sequel/model/associations.rb:487:in `fetch'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sequel-4.13.0/lib/sequel/model/associations.rb:487:in `cached_fetch'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sequel-4.13.0/lib/sequel/model/associations.rb:60:in `associated_dataset'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sequel-4.13.0/lib/sequel/model/associations.rb:196:in `association_dataset_for'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sequel-4.13.0/lib/sequel/model/associations.rb:199:in `block in <class:AssociationReflection>'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sequel-4.13.0/lib/sequel/model/associations.rb:2042:in `instance_exec'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sequel-4.13.0/lib/sequel/model/associations.rb:2042:in `_dataset'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sequel-4.13.0/lib/sequel/model/associations.rb:1717:in `block in def_association_instance_methods'
14:09:13 web.1                | 	/Users/rose/.embedded_toshi/latest/lib/toshi/models/block.rb:299:in `block in to_hash_collection'
14:09:13 web.1                | 	/Users/rose/.embedded_toshi/latest/lib/toshi/models/block.rb:274:in `each'
14:09:13 web.1                | 	/Users/rose/.embedded_toshi/latest/lib/toshi/models/block.rb:274:in `to_hash_collection'
14:09:13 web.1                | 	/Users/rose/.embedded_toshi/latest/lib/toshi/models/block.rb:266:in `to_hash'
14:09:13 web.1                | 	/Users/rose/.embedded_toshi/latest/lib/toshi/web/api.rb:87:in `block in <class:Api>'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `call'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1603:in `block in compile!'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `[]'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (3 levels) in route!'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:985:in `route_eval'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:966:in `block (2 levels) in route!'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1006:in `block in process_route'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `catch'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1004:in `process_route'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:964:in `block in route!'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `each'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:963:in `route!'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1076:in `block in dispatch!'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1073:in `dispatch!'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `block in call!'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `block in invoke'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `catch'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1058:in `invoke'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:898:in `call!'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:886:in `call'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/rack-1.5.2/lib/rack/nulllogger.rb:9:in `call'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:180:in `call'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:2014:in `call'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `block in call'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1788:in `synchronize'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:1478:in `call'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/rack-1.5.2/lib/rack/urlmap.rb:65:in `block in call'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `each'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `call'
14:09:13 web.1                | 	/Users/rose/.embedded_toshi/latest/lib/toshi/web/websocket.rb:45:in `call'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/rack-1.5.2/lib/rack/urlmap.rb:65:in `block in call'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `each'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/rack-1.5.2/lib/rack/urlmap.rb:50:in `call'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/bugsnag-2.2.2/lib/bugsnag/rack.rb:36:in `call'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/puma-2.9.0/lib/puma/rack_patch.rb:13:in `call'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/sinatra-1.4.5/lib/sinatra/base.rb:217:in `call'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/puma-2.9.0/lib/puma/configuration.rb:71:in `call'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/puma-2.9.0/lib/puma/server.rb:490:in `handle_request'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/puma-2.9.0/lib/puma/server.rb:361:in `process_client'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/puma-2.9.0/lib/puma/server.rb:254:in `block in run'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/puma-2.9.0/lib/puma/thread_pool.rb:92:in `call'
14:09:13 web.1                | 	/Users/rose/.gem/ruby/2.0.0/ruby/2.0.0/gems/puma-2.9.0/lib/puma/thread_pool.rb:92:in `block in spawn_thread'
14:09:13 web.1                | 127.0.0.1 - - [02/Feb/2015 14:09:13] "GET /api/v0/blocks/101/transactions HTTP/1.1" 500 30 0.0350
14:09:13 web.1                | 127.0.0.1 - - [02/Feb/2015 14:09:13] "GET /api/v0/blocks/98/transactions HTTP/1.1" 200 1829 0.0629
```

**Comment by mattly** [comment]
This looks to be a problem with `autoload` and the Transaction model class not being referenced before an instance of Transaction is automagically created from a database record. A hacky, if effective solution would be to reference `Transaction` in the to_hash_collection method before https://github.com/coinbase/toshi/blob/master/lib/toshi/models/block.rb#L299
