### ISSUE TITLE
#vagrant up error while starting

### ISSUE THREAD

**Issue by amitprasadom** [coinbase/toshi#158]
vagrant up
/usr/share/vagrant/plugins/provisioners/docker/plugin.rb:13:in `require_relative': /usr/share/vagrant/plugins/provisioners/docker/config.rb:23: syntax error, unexpected tPOW (SyntaxError)
      def run(name, **options)
                      ^
/usr/share/vagrant/plugins/provisioners/docker/config.rb:43: syntax error, unexpected keyword_end, expecting $end
	from /usr/share/vagrant/plugins/provisioners/docker/plugin.rb:13:in `block in <class:Plugin>'
	from /usr/lib/ruby/vendor_ruby/vagrant/registry.rb:27:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/registry.rb:27:in `get'
	from /usr/share/vagrant/plugins/kernel_v2/config/vm_provisioner.rb:34:in `initialize'
	from /usr/share/vagrant/plugins/kernel_v2/config/vm.rb:223:in `new'
	from /usr/share/vagrant/plugins/kernel_v2/config/vm.rb:223:in `provision'
	from /home/diksha/toshi/toshi/Vagrantfile:20:in `block in <top (required)>'
	from /usr/lib/ruby/vendor_ruby/vagrant/config/v2/loader.rb:37:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/config/v2/loader.rb:37:in `load'
	from /usr/lib/ruby/vendor_ruby/vagrant/config/loader.rb:104:in `block (2 levels) in load'
	from /usr/lib/ruby/vendor_ruby/vagrant/config/loader.rb:98:in `each'
	from /usr/lib/ruby/vendor_ruby/vagrant/config/loader.rb:98:in `block in load'
	from /usr/lib/ruby/vendor_ruby/vagrant/config/loader.rb:95:in `each'
	from /usr/lib/ruby/vendor_ruby/vagrant/config/loader.rb:95:in `load'
	from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:265:in `config_global'
	from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:519:in `block in action_runner'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:36:in `call'
	from /usr/lib/ruby/vendor_ruby/vagrant/action/runner.rb:36:in `run'
	from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:283:in `hook'
	from /usr/lib/ruby/vendor_ruby/vagrant/environment.rb:139:in `initialize'
	from /usr/bin/vagrant:105:in `new'
	from /usr/bin/vagrant:105:in `<main>'

**Comment by hudon** [comment]
What's your  `ruby --version`?

**Comment by mamachanko** [comment]
@hudon 1.9.3.p484

**Comment by Grprashanthkumar** [comment]
could anyone please let me know if there is any fix for this issue? 

I am working on Ubuntu 14 and installed vagrant 1.4.7 . I have updated the ruby version to the latest one and I still face the same issue.. can anyone please help me with it?
