### ISSUE TITLE
Error "NameError: global name 'WindowsError' is not defined"

### ISSUE THREAD

**Issue by frz-dev** [coinbase/toshi#242]
When executing the first build command: "docker-compose build" 
I get this error output:

redis uses an image, skipping
db uses an image, skipping
Building transactionworker
Traceback (most recent call last):
  File "/usr/bin/docker-compose", line 9, in <module>
    load_entry_point('docker-compose==1.6.2', 'console_scripts', 'docker-compose')()
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 56, in main
    command.sys_dispatch()
  File "/usr/lib/python2.7/site-packages/compose/cli/docopt_command.py", line 23, in sys_dispatch
    self.dispatch(sys.argv[1:], None)
  File "/usr/lib/python2.7/site-packages/compose/cli/docopt_command.py", line 26, in dispatch
    self.perform_command(*self.parse(argv, global_options))
  File "/usr/lib/python2.7/site-packages/compose/cli/main.py", line 191, in perform_command
    handler(project, command_options)
  File "/usr/lib64/python2.7/contextlib.py", line 35, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python2.7/site-packages/compose/cli/command.py", line 34, in friendly_error_message
    if call_silently(['which', 'docker']) != 0:
  File "/usr/lib/python2.7/site-packages/compose/cli/utils.py", line 45, in call_silently
    except WindowsError:
NameError: global name 'WindowsError' is not defined

I work on Linux Fedora 23 64-bit.
I looked for a solution, but most suggestions implies code changes.

Is there a workaround for this?

**Comment by frz-dev** [comment]
I solved by:
- remove "docker" and "docker-compose"
- reinstall Docker (by following [these instructions](https://docs.docker.com/engine/installation/linux/fedora/)), and adding my user to the docker group
- reinstall "docker-compose" (via dnf)
- restart
